//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "bills")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub creator_id: i32,
    pub unique_id: String,
    #[sea_orm(column_type = "Float")]
    pub total_amount: f32,
    pub status: String,
    pub category: String,
    pub created_at: DateTime,
    pub due_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::billee::Entity")]
    Billee,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatorId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::user_bills_joined::Entity")]
    UserBillsJoined,
}

impl Related<super::billee::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Billee.def()
    }
}

impl Related<super::user_bills_joined::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBillsJoined.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_bills_joined::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_bills_joined::Relation::Bills.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
